#ifndef __KT_FMS_UTIL_H__
#define __KT_FMS_UTIL_H__

typedef enum
{
	KT_FMS_UTIL_RET_FAIL = -1,
	KT_FMS_UTIL_RET_SUCCESS = 0,
	KT_FMS_UTIL_RET_DONE = KT_FMS_UTIL_RET_SUCCESS,
	KT_FMS_UTIL_RET_SERVER_OK,
	KT_FMS_UTIL_RET_SERVER_NOK,
	KT_FMS_UTIL_RET_SERVER_ERR_AND_CHK,
}KT_FMS_UTIL_RET;



#endif


